=== VargaEszter11/F9PSJAWebXML/F9PSJA_XMLTask/F9PSJA_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="NeptunAdatok">
    <xs:complexType>
      <xs:sequence>

        <!-- Hallgatók -->
        <xs:element name="Hallgato" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Neptun" type="xs:string"/>
              <xs:element name="Nev" type="xs:string"/>
              <xs:element name="SzuletesiDatum" type="xs:date"/>
              <xs:element name="Cim">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Varos" type="xs:string"/>
                    <xs:element name="Utca" type="xs:string"/>
                    <xs:element name="Hazszam" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Email" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="Telefonszam" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="hid" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>

        <!-- Kurzusok -->
        <xs:element name="Kurzus" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Kod" type="xs:string"/>
              <xs:element name="Nev" type="xs:string"/>
              <xs:element name="Kredit" type="xs:positiveInteger"/>
              <xs:element name="Tipus" type="xs:string"/>
              <xs:element name="TanarRef" type="xs:IDREF"/>
            </xs:sequence>
            <xs:attribute name="kid" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>

        <!-- Oktatók -->
        <xs:element name="Oktato" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nev" type="xs:string"/>
              <xs:element name="Titulus" type="xs:string"/>
              <xs:element name="Beosztas" type="xs:string"/>
              <xs:element name="Email" type="xs:string"/>
              <xs:element name="IrodaRef" type="xs:IDREF"/>
            </xs:sequence>
            <xs:attribute name="oid" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>

        <!-- Tanszékek -->
        <xs:element name="Tanszek" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nev" type="xs:string"/>
              <xs:element name="Kod" type="xs:string"/>
              <xs:element name="Epulet" type="xs:string"/>
              <xs:element name="Telefon" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="did" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>

        <!-- Irodák -->
        <xs:element name="Iroda" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Epuletszam" type="xs:string"/>
              <xs:element name="Szoba" type="xs:string"/>
              <xs:element name="EpuletNev" type="xs:string"/>
              <xs:element name="Megjegyzes" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="iid" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>

        <!-- Beiratkozások -->
        <xs:element name="Beiratkozas" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Felev" type="xs:string"/>
              <xs:element name="Osztalyzat" type="xs:integer"/>
              <xs:element name="Teljesitve" type="xs:string"/>
              <xs:element name="Jeloles" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="bid" type="xs:ID" use="required"/>
            <xs:attribute name="hallgatoRef" type="xs:IDREF" use="required"/>
            <xs:attribute name="kurzusRef" type="xs:IDREF" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>

    <!-- Egyediség- és hivatkozás-kényszerek -->
    <xs:key name="HallgatoKey">
      <xs:selector xpath="Hallgato"/>
      <xs:field xpath="@hid"/>
    </xs:key>

    <xs:key name="KurzusKey">
      <xs:selector xpath="Kurzus"/>
      <xs:field xpath="@kid"/>
    </xs:key>

    <xs:key name="OktatoKey">
      <xs:selector xpath="Oktato"/>
      <xs:field xpath="@oid"/>
    </xs:key>

    <xs:key name="IrodaKey">
      <xs:selector xpath="Iroda"/>
      <xs:field xpath="@iid"/>
    </xs:key>

    <xs:keyref name="Beiratkozas_HallgatoRef" refer="HallgatoKey">
      <xs:selector xpath="Beiratkozas"/>
      <xs:field xpath="@hallgatoRef"/>
    </xs:keyref>

    <xs:keyref name="Beiratkozas_KurzusRef" refer="KurzusKey">
      <xs:selector xpath="Beiratkozas"/>
      <xs:field xpath="@kurzusRef"/>
    </xs:keyref>

  </xs:element>

</xs:schema>

=== VargaEszter11/F9PSJAWebXML/F9PSJA_XMLTask/F9PSJA_XML_modified.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<NeptunAdatok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="F9PSJA_XMLSchema.xsd">
    
  <!-- Hallgató 1 -->
    
  <Hallgato hid="H1">
        
    <Neptun>KABC12</Neptun>
        
    <Nev>Horváth Anna Mária</Nev>
        
    <SzuletesiDatum>2001-03-15</SzuletesiDatum>
        
    <Cim>
            
      <Varos>Debrecen</Varos>
            
      <Utca>Piac utca</Utca>
            
      <Hazszam>5</Hazszam>
          
    </Cim>
        
    <!-- Többértékű tulajdonság -->
        
    <Email>anna.horvath@gmail.com</Email>
        
    <Email>horvath.anna@uni.hu</Email>
        
    <!-- Többértékű tulajdonság -->
        
    <Telefonszam>+36-30-123-4567</Telefonszam>
        
    <Telefonszam>+36-20-765-4321</Telefonszam>
      
  </Hallgato>
    
  <!-- Hallgató 2 -->
    
  <Hallgato hid="H2">
        
    <Neptun>MBXY34</Neptun>
        
    <Nev>Kovacs Balazs</Nev>
        
    <SzuletesiDatum>1999-11-02</SzuletesiDatum>
        
    <Cim>
            
      <Varos>Budapest</Varos>
            
      <Utca>Fovam ter</Utca>
            
      <Hazszam>8</Hazszam>
          
    </Cim>
        
    <Email>balazs.kovacs@gmail.com</Email>
        
    <Telefonszam>+36-70-111-2222</Telefonszam>
      
  </Hallgato>
    
  <!-- Kurzus 1 -->
    
  <Kurzus kid="K1">
        
    <Kod>INF1</Kod>
        
    <Nev>Bevezetés az informatikába</Nev>
        
    <Kredit>5</Kredit>
        
    <Tipus>Előadás</Tipus>
        
    <TanarRef>TA1</TanarRef>
     
    <!-- FK: tanar aki oktatja -->
      
  </Kurzus>
    
  <!-- Kurzus 2 -->
    
  <Kurzus kid="K2">
        
    <Kod>JAVA2</Kod>
        
    <Nev>Haladó Java</Nev>
        
    <Kredit>6</Kredit>
        
    <Tipus>Gyakorlat</Tipus>
        
    <TanarRef>TA2</TanarRef>
      
  </Kurzus>
  <Kurzus kid="K3">
    <Kod>WEB3</Kod>
    <Nev>Webprogramozás alapjai</Nev>
    <Kredit>4</Kredit>
    <Tipus>Előadás</Tipus>
    <TanarRef>TA1</TanarRef>
  </Kurzus>
    
  <!-- Oktató 1 -->
    
  <Oktato oid="TA1">
        
    <Nev>Dr. Szabo Gabor</Nev>
        
    <Titulus>Egyetemi docens</Titulus>
        
    <Beosztas>Szoftverfejlesztés</Beosztas>
        
    <Email>szabo.gabor@inf.unideb.hu</Email>
        
    <IrodaRef>I10</IrodaRef>
     
    <!-- FK az Iroda elemre -->
      
  </Oktato>
    
  <!-- Oktató 2 -->
    
  <Oktato oid="TA2">
        
    <Nev>Prof. Nagy Erzsebet</Nev>
        
    <Titulus>egyetemi tanár</Titulus>
        
    <Beosztas>Adatbázisok</Beosztas>
        
    <Email>erzsebet.nagy@uni.hu</Email>
        
    <IrodaRef>I11</IrodaRef>
      
  </Oktato>
    
  <!-- Tanszék1 -->
    
  <Tanszek tid="D1">
        
    <Nev>Informatikai Tanszek</Nev>
        
    <Kod>INF</Kod>
        
    <Epulet>A épület</Epulet>
        
    <Telefon>+36-52-444-000</Telefon>
      
  </Tanszek>
    
  <!-- Tanszék 2 -->
    
  <Tanszek tid="D2">
        
    <Nev>Matematika Tanszek</Nev>
        
    <Kod>MTA</Kod>
        
    <Epulet>B épület</Epulet>
        
    <Telefon>+36-52-444-100</Telefon>
      
  </Tanszek>
    
  <!-- Iroda 1 -->
    
  <Iroda iid="I10">
        
    <Epuletszam>A1</Epuletszam>
        
    <Szoba>203</Szoba>
        
    <EpuletNev>Főépület</EpuletNev>
        
    <Megjegyzes>Az oktatók irodája</Megjegyzes>
      
  </Iroda>
    
  <!-- Iroda 2 -->
    
  <Iroda iid="I11">
        
    <Epuletszam>B2</Epuletszam>
        
    <Szoba>101</Szoba>
        
    <EpuletNev>Matematika épület</EpuletNev>
        
    <Megjegyzes>Közös használatú iroda</Megjegyzes>
      
  </Iroda>
    
  <!-- Beiratkozas 1 -->
    

  
  <!-- Beiratkozas 2 -->
    
  <Beiratkozas bid="B2" hallgatoRef="H2" kurzusRef="K2">
        
    <Felev>2024/2</Felev>
        
    <Osztalyzat>5</Osztalyzat>
        
    <Teljesitve>Igen</Teljesitve>
        
    <Jeloles>Gyakorlat teljesítve</Jeloles>
      
  </Beiratkozas>
    
  <!-- Beiratkozas 3 -->
    
  <Beiratkozas bid="B3" hallgatoRef="H1" kurzusRef="K2">
        
    <Felev>2025/1</Felev>
        
    <Osztalyzat>3</Osztalyzat>
        
    <Teljesitve>Nem</Teljesitve>
        
    <Jeloles>Pótvizsga szükséges</Jeloles>
      
  </Beiratkozas>
  
</NeptunAdatok>
